### ISSUE TITLE
DateTimeParseException

### ISSUE THREAD

**Issue by marijncv** [kaiko-ai/spark-dicom#25]
I'm getting the below error message when trying to read DICOM files from the TCIA gs bucket.
```
java.time.format.DateTimeParseException: Text '122734.625000' could not be parsed, unparsed text found at index 10
```

Code to reproduce (pyspark):
```
APOLLO_FILE_PATH = "gs://gcs-public-data--healthcare-tcia-apollo/dicom/"
apollo_df = spark.read.format("dicomFile").option("recursiveFileLookup", "true").load(APOLLO_FILE_PATH)
apollo_df.collect()
```

**Comment by robopoc** [comment]
we could also catch parse exceptions and report on those in an "parse error" column instead?

I've seen this work well with big data on not so well defined data sources (due to DICOM "semi" standard in this case).
