### ISSUE TITLE
Read Private & Sequence tags as JSON with Keyword (str) as key instead of Tag (int)

### ISSUE THREAD

**Issue by marijncv** [kaiko-ai/spark-dicom#47]
To make the private and sequence tags more usable, the JSON should use the keyword of the tag as keys instead of the tag itself

**Comment by GuillaumeDesforges** [comment]
Can we find a mapping from private tag (int) to keyword (str) ?

Maybe this should still be optional (but activated by default) as some people might work with private tags (int) that are "non-standard"?

**Comment by marijncv** [comment]
Agree, it should be optional. For private tags maybe the feature is less relevant since it requires this tag <-> keyword mapping like you mentioned. But for the SQ VR tags it's a lot more feasible since we know the mapping there

**Comment by GuillaumeDesforges** [comment]
Do we want to address https://github.com/kaiko-ai/spark-dicom/pull/48#discussion_r812785954 ?
